### ISSUE TITLE
NPM version out of date

### ISSUE THREAD

**Issue by Mjtlittle** [lucaburgio/iconoir#111]
It seems the latest version is not published to NPM.

- `iconoir` (? < 4.6): https://www.npmjs.com/package/iconoir
- `iconoir-react` (4.4.0 < 4.6): https://www.npmjs.com/package/iconoir-react
- `iconoir-react-native` (4.4.0 < 4.6): https://www.npmjs.com/package/iconoir-react-native

_edit: Also if you do decide to release newer versions of these packages on npm, it may make sense to use the icon pack version as the package.json version. As currently `iconoir-react-native` is using icons 4.4 but is on version 2.1._

---

Love the icons btw. I plan on using them exclusively on my personal website (made with svelte). Appreciate the work that has gone into these; the line aesthetic is not common in other icon sets.

**Comment by indaco** [comment]
For Svelte you could use 

https://www.npmjs.com/package/@indaco/svelte-iconoir

Hope to update the lib to the latest (v4.6) on tomorrow

**Comment by Mjtlittle** [comment]
I just realized I can install git repos like npm packages: `npm install https://github.com/lucaburgio/iconoir.git#commit`. This solves my issue for the time being, but it would be nice to still have it mirrored on npm for insurance (default immutable versioning).

**Comment by Mjtlittle** [comment]
@indaco This is great! I actually made a wrapper similar to you have here for formatting the svgs in my current project. Im going to stick with what I have now incase I want to drop any divergent svg icons in my site. But for new projects ill definitely consider this!

**Comment by indaco** [comment]
@Mjtlittle  FYI `svelte-iconoir` is now on iconoir v4.6

**Comment by lucaburgio** [comment]
@indaco It would be great to make the Svelte one official here! I still have to reply to you in DM. I'm going to do that soon 👍

**Comment by lucaburgio** [comment]
@sammarks What do you think? Is it possible to auto-sync the NPM libraries version with the one in the repo?

**Comment by sammarks** [comment]
@lucaburgio I'm assuming you're talking about the v4.6.0 inside the main `package.json`?

How do you normally go about incrementing the version for the main icon set (so how would you have gone about incrementing to v4.6.0 from v4.5.x)? Do you just create a new release inside GitHub, or do you manually create the tag in something like GitHub desktop?

We could update the CI script so instead of creating a new minor release with every commit to master, it would create a new release every time a new tag is created. Arguably, creating a release with each push to master isn't the greatest solution but it was the "quick and dirty" to get the NPM packages updated.

**Comment by lucaburgio** [comment]
@sammarks Totally understand and agree, the `quick and dirty` is already an improvement to what we had before.

What I do is create a new release and its tag on GitHub.

> it would create a new release every time a new tag is created.

I think this would be perfect. What do you think?
