### ISSUE TITLE
Update `iconoir` npm package to the latest version

### ISSUE THREAD

**Issue by DanielHZhang** [lucaburgio/iconoir#139]
After reading #111, I noticed that the `iconoir` package does not seem to get updated with new releases, unlike the `iconoir-react` and `iconoir-react-native` packages. Is there a reason why this package is not included in the release action pipeline? I'd be happy to put up a PR that adds it to the prepublish script.

Thanks for making these icons open source, they're really great!

**Comment by sammarks** [comment]
I suppose it wouldn't be that difficult to add the main package to the publish script. It looks like it's just:

- All of the icon SVGs inside `icons`
- The license & README

I could update it to include the automatically-generated CSS as well, since that seems like an easy win.

I'll look into getting a PR up for that this week.
